Support for soft clustering
GuyAllard/markov_clustering pull request #16
Opened 2019-03-11 12:55 UTC by Moonire

add's the option to keep overlapping nodes in the clustering or to delete theme by setting keep_overlap either to True or False. Displaying a message informing the user that there are overlaps in case he is using the default hard clustering method.

2019-03-12 08:06 UTC, GuyAllard requested changes

2019-03-12 08:06 UTC, GuyAllard commented on markov_clustering/mcl.py
> +    :param keep_overlap: If true, unables soft clustering
use 'enable' instead of 'unable'

2019-03-12 08:06 UTC, GuyAllard commented on markov_clustering/mcl.py
> +        printer.print("Clustering contains overlapping, to unable soft clustering set keep_overlap to True")
use 'enable' instead of 'unable'

2019-03-13 08:04 UTC, GuyAllard commented
Hi Mounir, Thanks for submitting this PR.

I would like to approach this slightly differently to your implementation.

Specifically, I would like to perform the identification and removal of overlap nodes in a separate function which is called when keep_overlap=False
Doing so will make the code easier to maintain and test.

What are your thoughts on this approach?

2019-03-13 21:03 UTC, Moonire commented
It seems perfectly reasonable to me.
In this case I think a ternary operator that will call the function when keep_overlap=False will do the trick. I'm take care of that asap.

Do you want to change the warning message ? I know i'm not good with writing warnings haha..

2022-10-18 21:13 UTC, closed without merging

2024-02-06 21:51 UTC, codykingham commented
It seems a fix for this was never implemented?